/**
 * Type Definitions for Event Sorter Application
 *
 * This file contains TypeScript interfaces that define the shape of data
 * used throughout the application. These types ensure type safety and
 * provide autocompletion in the IDE.
 */

/**
 * ExtractedEventData Interface
 *
 * Represents the data extracted from an event poster image by the AI service.
 * All fields are nullable because the AI might not be able to extract every piece
 * of information from every poster.
 *
 * Used in: AI extraction service, upload page
 */
export interface ExtractedEventData {
  name: string | null;        // Event title/name extracted from the poster
  date: string | null;        // Event date (format: YYYY-MM-DD)
  time: string | null;        // Event time (format: HH:MM)
  location: string | null;    // Venue or address of the event
  ticketUrl: string | null;   // URL to purchase tickets (if found on poster)
  description: string | null; // Brief description of the event
}

/**
 * EventFormData Interface
 *
 * Represents the data submitted when creating or editing an event.
 * This is the shape of form data before it's sent to the API.
 * Optional fields (marked with ?) can be omitted.
 *
 * Used in: EventForm component, create/update API routes
 */
export interface EventFormData {
  name: string;           // Required: Event name
  description?: string;   // Optional: Event description
  location?: string;      // Optional: Event location/venue
  date: string;          // Required: Event date (YYYY-MM-DD format)
  time?: string;         // Optional: Event time (HH:MM format)
  ticketUrl?: string;    // Optional: URL for ticket purchase
  imageUrl?: string;     // Optional: URL of the uploaded event poster image
}

/**
 * Event Interface
 *
 * Represents a complete event object as stored in the database and returned by APIs.
 * This is the full event shape including the database-generated ID and metadata.
 *
 * Fields with `| null` can exist but have no value (different from undefined/missing).
 *
 * Used in: Event display components, API responses, state management
 */
export interface Event {
  id: string;                        // Unique identifier (generated by database)
  name: string;                      // Event name/title
  description?: string | null;       // Event description
  location?: string | null;          // Event venue/location
  date: string;                      // Event date (ISO string format)
  time?: string | null;              // Event time
  ticketUrl?: string | null;         // Ticket purchase URL
  imageUrl?: string | null;          // Event poster image URL
  googleEventId?: string | null;     // Google Calendar event ID (if synced)
  deletedAt?: string | null;         // Soft delete timestamp (null = not deleted)
}
